### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by jantman** [djcf/rtl8192eu-xbian#1]
Where is the source code for this driver?

From what I can tell it's almost certainly licensed under the GPL, which requires you to distribute (or provide a source for) the source code when distributing the binary.

**Comment by djcf** [comment]
I believe it's a compiled binary of the driver [here](https://github.com/romcyncynatus/rtl8192eu). To be honest, this repository was a convenience measure for my own use so that I didn't have to recompile and install the buildchain on all of my raspberry devices. In any case I believe it's obsolete now: this driver should work out of box with the latest xbian.
